### ISSUE TITLE
FlexibleSize不兼容1920x1080分辨率

### ISSUE THREAD

**Issue by zooPanda** [maoqxxmm/scriptable-jsx#3]
在macOS上使用scriptable运行脚本，无法渲染小组件。
希望能够兼容

**Comment by maoqxxmm** [comment]
主要是不知道 macOS 上不同分辨率对应的小组件尺寸是多少……如果有规范的话我可以加上，没有的话目前你也可以参考 [device-data.ts](https://github.com/maoqxxmm/scriptable-jsx/blob/master/src/utils/size/device-data.ts) 这里的做法，注册一个自定义的数据上去。

```jsx
import { WidgetSizeCenter } from 'scriptable-jsx';

WidgetSizeCenter.register("1920x1080", [xx, xx], [xx, xx], [xx, xx]);
```

**Comment by maoqxxmm** [comment]
在不知道精确尺寸数据的情况下 FlexibleSize 是无法达到预期效果的……我抽空再搜搜有没有相关的数据

**Comment by zooPanda** [comment]
辛苦。

其实在没有准确数据的情况下，可以有一个缺省值，不然在macOS上直接无法渲染了。


毛球 ***@***.***>于2022年6月15日 周三15:58写道：

**Comment by maoqxxmm** [comment]
> 

确实，我可以提供一个缺省值然后 log 一下警告

**Comment by maoqxxmm** [comment]
see [fix](https://github.com/maoqxxmm/scriptable-jsx/commit/3d45d8f2f5b1783f88c2569dd64531d836fd3cef)
